FROM pytorch/pytorch:1.0.1-cuda10.0-cudnn7-runtime

RUN pip install torchvision==0.2.2
RUN pip install pandas==0.24.2
RUN pip install Pillow==6.2.1
RUN pip install scipy==1.2.1
RUN pip install matplotlib==3.1.2
RUN pip install scikit-learn==0.22
RUN pip install gensim==3.8.1
RUN pip install h5py==2.10.0

WORKDIR /workspace